#!groovy
library 'kypseli'
pipeline {
    options { 
        buildDiscarder(logRotator(numToKeepStr: '7')) 
        skipDefaultCheckout() 
    }
    agent none
    stages {
        stage('Build and Push Image') {
            steps {
                dockerFileDefaults()
            }
        }
    }
}
